Husky: Small test to check test data doesn't contain Booking IDs
They're sentive and we shouldn't commit them.

NOTE: This test is not gonna cover all possible ways of accidentally
commit sensitve data but it's a start and it's better than nothing.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,3 +3,11 @@
 
 export NODE_ENV=dev
 npx lint-staged && npx tsc && npm test
+
+# Check test data doesn't contain booking IDs
+if grep -q book server/testData/s3Bucket/*/*; then
+  echo "FAIL: Possibly booking IDs/sensitive information in test data"
+  exit 1
+# else
+  # OK: Test data shouldn't contain booking IDs
+fi
